// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1S6vfBNAxlbE1wB9clHtMQqEi_w1EqOo',
    appId: '1:271921492379:web:e17991706aed6389de313e',
    messagingSenderId: '271921492379',
    projectId: 'mp05-a7276',
    authDomain: 'mp05-a7276.firebaseapp.com',
    databaseURL: 'https://mp05-a7276-default-rtdb.firebaseio.com',
    storageBucket: 'mp05-a7276.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA68aLW5UdXP3jVVMOu6aCGxMs5plVBVTk',
    appId: '1:271921492379:android:32d124816dfbce6ade313e',
    messagingSenderId: '271921492379',
    projectId: 'mp05-a7276',
    databaseURL: 'https://mp05-a7276-default-rtdb.firebaseio.com',
    storageBucket: 'mp05-a7276.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2POjqmD2G2Rz613gTDELbKRq2VWysd70',
    appId: '1:271921492379:ios:416a9e0b818a3d8fde313e',
    messagingSenderId: '271921492379',
    projectId: 'mp05-a7276',
    databaseURL: 'https://mp05-a7276-default-rtdb.firebaseio.com',
    storageBucket: 'mp05-a7276.firebasestorage.app',
    iosBundleId: 'com.example.f09RecursosNativos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2POjqmD2G2Rz613gTDELbKRq2VWysd70',
    appId: '1:271921492379:ios:62bc6ab41dac2ff9de313e',
    messagingSenderId: '271921492379',
    projectId: 'mp05-a7276',
    databaseURL: 'https://mp05-a7276-default-rtdb.firebaseio.com',
    storageBucket: 'mp05-a7276.firebasestorage.app',
    iosBundleId: 'com.example.recursosnativos.mp5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1S6vfBNAxlbE1wB9clHtMQqEi_w1EqOo',
    appId: '1:271921492379:web:a61831a57ec928ddde313e',
    messagingSenderId: '271921492379',
    projectId: 'mp05-a7276',
    authDomain: 'mp05-a7276.firebaseapp.com',
    databaseURL: 'https://mp05-a7276-default-rtdb.firebaseio.com',
    storageBucket: 'mp05-a7276.firebasestorage.app',
  );
}
